config/routes.rb
Rails.application.routes.draw do
  get 'debts/new'

  
  root 'enteros#new'
  resources :sessions, only:[:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  
  resources :enteros do
      collection do
        get 'showRecipts', to: 'enteros#showRecipts'
        get 'buildpdf', to:'enteros#buildPdf'
        get 'showEntero', to:'enteros#showEntero'
        get 'insertServices', to:'enteros#insertServices'
        get 'deleteServices', to:'enteros#deleteServices'
        post 'putService', to:'enteros#putService'
        delete 'popService', to:'enteros#popService'
      end
  end
  
  resources :concessionaries do
    collection do
      get 'get_byName', to:'concessionaries#get_byName'
    end
  end
  
  resources :vehicles do
      resources :debts, only: [:create, :destroy]
  end
  

end

app/models/concessionary.rb
class Concessionary < ActiveRecord::Base
    has_many :vehicles
    has_many :Enteros
end

app/controllers/concessionaries_controller.rb
class ConcessionariesController < ApplicationController
  before_action :set_concessionary, only: [:show, :edit, :update, :destroy]
  protect_from_forgery except: :get_byName
  
  # GET /concessionaries
  # GET /concessionaries.json
  def index
    @concessionaries = Concessionary.all.order(:name).paginate(page: params[:page], per_page:20)
  end

  # GET /concessionaries/1
  # GET /concessionaries/1.json
  def show
  end

  # GET /concessionaries/new
  def new
    @concessionary = Concessionary.new
  end

  # GET /concessionaries/1/edit
  def edit
  end

  # POST /concessionaries
  # POST /concessionaries.json
  def create
    @concessionary = Concessionary.new(concessionary_params)

    respond_to do |format|
      if @concessionary.save
        format.html { redirect_to @concessionary, notice: 'Concessionario creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @concessionary }
      else
        format.html { render :new }
        format.json { render json: @concessionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concessionaries/1
  # PATCH/PUT /concessionaries/1.json
  def update
    respond_to do |format|
      if @concessionary.update(concessionary_params)
        format.html { redirect_to @concessionary, notice: 'Concessionario actualizado.' }
        format.json { render :show, status: :ok, location: @concessionary }
      else
        format.html { render :edit }
        format.json { render json: @concessionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concessionaries/1
  # DELETE /concessionaries/1.json
  def destroy
    @concessionary.destroy
    respond_to do |format|
      format.html { redirect_to concessionaries_url, notice: 'Concessionario fue borrado.' }
      format.json { head :no_content }
    end
  end
  
  def get_byName
    #byebug
    @concessionaries = Concessionary.where("name LIKE ?",'%'+params[:name]+'%')
    
    respond_to do |format|
      format.js {}
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concessionary
      @concessionary = Concessionary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concessionary_params
      params.require(:concessionary).permit(:name, :telephone)
    end
end

app/helpers/concessionaries_helper.rb
module ConcessionariesHelper
end

app/views/concessionaries/_form.html.erb
<%= form_for(@concessionary) do |f| %>
  <% if @concessionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concessionary.errors.count, "error") %> prohibited this concessionary from being saved:</h2>

      <ul>
      <% @concessionary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='container'>
    <div class='row'>
      <div class="col-xs-4 col-md-4">
        <%= f.label :name %><br>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      <div class="col-xs-2 col-md-2">
        <%= f.label :telephone %><br>
        <%= f.text_field :telephone, class:'form-control' %>
      </div>
    </div>
    <div class='row'>
      <div class="col-xs-2 col-md-2">
        <br>
        <br>
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/concessionaries/_show_data.html.erb
<div class='col-xs col-md-1'></div>
<div class='col-xs col-md-10'>
    <div class="table-responsive no-margins">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Telephone</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
                <% @concessionaries.each do |concessionary| %>
                    <tr>
                        <td><%= concessionary.name %></td>
                        <td><%= concessionary.telephone %></td>
                        <td><%= link_to concessionary do %> <%= octicon 'eye', class:'rigth' %> <% end %></td>
                        <td><%= link_to edit_concessionary_path(concessionary) do %> <%= octicon 'pencil', class:'rigth' %> <% end %> </td>
                        <td><%= link_to concessionary, method: :delete, data: { confirm: 'Esta usted seguro?' } do %>
                            <%= octicon 'trashcan', class:'rigth' %>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>      
    </div>
</div>

app/views/concessionaries/edit.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs col-md-12 be-soft_gray'>
            <h1>Edicion de Concesionario</h1>            
        </div>
    </div>
</div>

<%= render 'form' %>
<br>
<br>
<div class='container'>
    <div class='row'>
        <div class='col-xs col-md-6 be-soft_gray'>
            <span class='pull-left'>
                <%= link_to 'Mostra', @concessionary, class:'btn btn-default btn-sm' %> |
                <%= link_to 'Regresar', concessionaries_path, class:'btn btn-default btn-sm' %>
            </span>
        </div>
    </div>
</div>

app/views/concessionaries/get_byName.js.erb
$(".cube").html("<%= escape_javascript(render('show_data')) %>");

app/views/concessionaries/index.html.erb
<div class='container'>
  <div class='row be-soft_gray'>
    <div class='col-xs col-md-4'>
      <h1>Lista Concesionarios</h1>      
    </div><div class='col-xs col-md-2'></div>
    <div class='col-xs col-md-6 be_round_soft_gray2'>
      <%= bootstrap_form_tag remote:true, url:'concessionaries/get_byName', method:'get', :html => {id:'search'} do |f| %>
        <%= f.text_field_with_bootstrap :name, label:'Busqueda de concesionario por nombre' %>
        <%= submit_tag 'Buscar', class:'btn btn-default btn-md srch' %>
      <% end %>
    </div>
  </div>
  <div class='row cube'></div>
  <div class='row'>
    <div class='col-xs col-md-1'></div>
    <div class='col-xs col-md-10'>
      <div class="table-responsive no-margins">
        <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Telefono</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @concessionaries.each do |concessionary| %>
            <tr>
              <td><%= concessionary.name %></td>
              <td><%= concessionary.telephone %></td>
              <td><%= link_to concessionary do %> <%= octicon 'eye', class:'rigth' %> <% end %></td>
              <td><%= link_to edit_concessionary_path(concessionary) do %> <%= octicon 'pencil', class:'rigth' %> <% end %> </td>
              <td><%= link_to concessionary, method: :delete, data: { confirm: 'Esta usted seguro?' } do %>
                    <%= octicon 'trashcan', class:'rigth' %>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>      
    </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs col-md-2'>
      <br>
      <%= link_to 'Nuevo', new_concessionary_path, class:'btn btn-default btn-md' %>
    </div>
    <div class='col-xs col-md-8'>
      <%= will_paginate @concessionaries, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/concessionaries/new.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs col-md-12 be-soft_gray'>
            <h1>Nuevo Concesionario</h1>
        </div>
    </div>
</div>
<%= render 'form' %>
<br>
<br>
<div class='container'>
    <div class='row'>
        <div class='col-xs col-md-12 be-soft_gray'>
            <%= link_to 'Regresar', concessionaries_path, class:'btn btn-default btn-lg' %>            
        </div> 
    </div>
</div>

app/views/concessionaries/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs col-md-8'>
      <p>
        <strong>Nombre:</strong>
        <%= @concessionary.name %>
      </p>
      
      <p>
        <strong>Telefono:</strong>
        <%= @concessionary.telephone %>
      </p>
    </div>
  </div>
  <br>
  <br>
  <div class='row'>
    <div class='col-xs col-md-12 be-soft_gray'>
      <%= link_to 'Editar', edit_concessionary_path(@concessionary), class:'btn btn-default btn-sm' %> |
      <%= link_to 'Regresar', concessionaries_path, class:'btn btn-default btn-sm' %>
    </div>
  </div>
</div>