config/routes.rb
Rails.application.routes.draw do
  get 'debts/new'

  
  root 'enteros#new'
  resources :sessions, only:[:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  
  resources :enteros do
      collection do
        get 'showRecipts', to: 'enteros#showRecipts'
        get 'buildpdf', to:'enteros#buildPdf'
        get 'showEntero', to:'enteros#showEntero'
        get 'insertServices', to:'enteros#insertServices'
        get 'deleteServices', to:'enteros#deleteServices'
        post 'putService', to:'enteros#putService'
        delete 'popService', to:'enteros#popService'
      end
  end
  
  resources :concessionaries do
    collection do
      get 'get_byName', to:'concessionaries#get_byName'
    end
  end
  
  resources :vehicles do
      resources :debts, only: [:create, :destroy]
  end
  

end

app/models/entero.rb
class Entero < ActiveRecord::Base
    belongs_to :concessionary
    # HUMANIZED_ATTRIBUTES = {taxpayer:'concessionario', service:'servicio', quantity:'cantidad', unit:'unidad'}
    # validates :taxpayer, :service, :unit, :quantity, presence: { message: 'No puede estar en blanco'}

    # def self.human_attribute_name(attr, options = {})
    #     HUMANIZED_ATTRIBUTES[attr.to_sym] || super
    # end
end

app/controllers/enteros_controller.rb
class EnterosController < ApplicationController
  before_action :set_entero, only: [:show, :edit, :update, :destroy]

  # GET /enteros
  # GET /enteros.json
  def index
    #@enteros = Entero.all.order(:id).paginate(page: params[:page], per_page:20)
    #@enteros = Entero.all.order(:created_at).order(:concessionary_id).paginate(page: params[:page], per_page:20)
    #@enteros = Entero.all.order(:concessionary_id).group(:created_at).paginate(page: params[:page], per_page:20)
    #@enteros = Entero.all.order(:created_at).order(:concessionary_id).group(:concessionary_id).paginate(page: params[:page], per_page:20)
    #@enteros = Entero.all.order(:concessionary_id).group(:created_at).paginate(page: params[:page], per_page:20)
    #@enteros = Entero.all.group(:created_at).group(:concessionary_id).paginate(page: params[:page], per_page:20)
    #@enteros = Entero.all.group(:concessionary_id).group(:created_at).paginate(page: params[:page], per_page:20)
    #@enteros = Entero.all.group(:concessionary_id,:created_at).order(created_at: :desc).paginate(page: params[:page], per_page:20)
    ###@enteros = Entero.all.group(:created_at).order(:concessionary_id).group(:concessionary_id).paginate(page: params[:page], per_page:20)
    # @enteros = Entero.where(concessionary_id:@e.concessionary).where("created_at LIKE '%2017-04-07 %'").group(:created_at).paginate(page: params[:page], per_page:20)
    #@enteros = Entero.all.group(:taxpayer, :created_at).order(created_at: :desc).paginate(page: params[:page], per_page:20)
    @enteros = Entero.all.group(:id, :taxpayer).order(created_at: :desc).paginate(page: params[:page], per_page:20)
  end

  # GET /enteros/1
  # GET /enteros/1.json
  def show
    respond_to do |format|
      if @entero.folio
        @enteros = Entero.where("folio LIKE ?","%#{@entero.folio}%")
        format.pdf do
          pdf = EnteroPdf.new(@enteros,@enteros.first.folio)
          send_data pdf.render,
            filename: "entero_relleno.pdf",
            type: 'application/pdf',
            disposition: 'inline'
        end
      else
        format.html
      end
    end
  end

  # GET /enteros/new
  def new
    @entero = Entero.new
    if Entero.last
      @folio = (Entero.last.folio.to_i+1).to_s.rjust(4,'0')
      elsif Folio.last
        @folio = (Folio.last.consecutive.to_i+1).to_s.rjust(4,'0')
    end
    @token = buildMAC(@folio)
  end

  # GET /enteros/1/edit
  def edit
  end

  # POST /enteros
  # POST /enteros.json
  def create
    @entero = Entero.new(entero_params)
      respond_to do |format|
        if @entero.save
          format.html  { redirect_to @entero, notice: 'Entero fue creado.' }
          format.json { render :show, status: :created, location: @entero }
          format.js
        else
          format.html { render :new }
          format.json { render json: @entero.errors, status: :unprocessable_entity }
        end
      end
  end
  
  # PATCH/PUT /enteros/1
  # PATCH/PUT /enteros/1.json
  def update
    respond_to do |format|
      if @entero.update(entero_params)
        format.html { redirect_to @entero, notice: 'Entero actualizado.' }
        format.json { render :show, status: :ok, location: @entero }
      else
        format.html { render :edit }
        format.json { render json: @entero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enteros/1
  # DELETE /enteros/1.json
  def destroy
    @entero.destroy
    respond_to do |format|
      format.html { redirect_to enteros_url, notice: 'Entero borrado.' }
      format.json { head :no_content }
    end
  end

  def insertServices
    respond_to do |format|
        format.js
      end
  end
  
  def putService
    if valid_folio?(params[:entero][:token],params[:entero][:folio])
      @entero = Entero.new(entero_params)
      @entero.concessionary = set_concessionary
      
      respond_to do |format|
        if @entero.save
          format.json { render :show, status: :created, location: @entero }
          format.js
        end
      end
    end
  end
  
  def deleteServices
    respond_to do |format|
      format.js
    end
  end
  
  def popService
    set_entero
    @entero.destroy
    respond_to do |format|
      format.json { head :no_content, notice: 'Entero was successfully destroyed.'}
      format.js
    end
  end
  
  def buildPdf
    respond_to do |format|
      format.js
    end
  end
  
  def showEntero
    @enteros = Entero.where id: params[:totals].split(',')
    respond_to do |format|
      if params[:tocken] == buildMAC(params[:f])
        format.html do
          
          pdf = EnteroPdf.new(@enteros,params[:f])
          send_data pdf.render,
            filename: "entero_relleno.pdf",
            type: 'application/pdf',
            disposition: 'inline'
          end
      else
        format.html {render plain: 'ISSUE'}
      end
    end
    
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entero
      @entero = Entero.find(params[:id])
    end
    
    def set_concessionary
      Concessionary.find_by name:entero_params[:taxpayer]
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def entero_params
      params.require(:entero).permit(:taxpayer, :service, :unit, :quantity, :folio)
    end
    
    def buildMAC(data)
      key = '65043d9d7c067285df44ac43eee30e35e1c2cf3eee352b338c6aabccbbdcaca9'
      digest = OpenSSL::Digest.new('sha256')
      OpenSSL::HMAC.hexdigest(digest, key, data)
    end
    
    def valid_folio?(token,folio)
      if buildMAC(folio) == token
        return true
      else
        return  false
      end
    end
end

app/helpers/enteros_helper.rb
module EnterosHelper
end

app/views/enteros/_form.html.erb
<%= form_for(@entero) do |f| %>
  <% if @entero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entero.errors.count, "error") %> prohibited this entero from being saved:</h2>

      <ul>
      <% @entero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container be-round_ligth_gray">
    <div class="row">
      <div class="col-xs-6 col-md-6">
        <%= f.label :NOMBRE %><br>
        <%= f.select :taxpayer, Concessionary.all.order(:name).pluck(:name),{}, {class:'btn btn-default dropdown-toggle', id:'taxpayer'} %>
      </div>
      <div class="col-xs-2 col-md-2"> 
        <%= f.label :UNIDAD %><br>
        <%= f.select :unit, [ ['TON.','1'], ['K.G.','2'], ['M3','3'], ['VEHICULO',4] ], {}, {class:'btn btn-default dropdown-toggle unit'} %>
      </div>
      <div class="col-xs-2 col-md-1">
        <%= f.label :CANTIDAD %><br>
        <%= f.text_field :quantity, class:'form-control cantidad' %>
      </div>
      <div class="col-xs-2 col-md-3" align='center'>
        <h2>FOLIO: <%= @folio %></h2>
        <%= hidden_field_tag 'token', @token %>
        <%= hidden_field_tag 'f', @folio %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-10 col-md-7">
        <%= f.label :servicio %><br>
        <%= f.select :service, 
        [ 
          ['DISPOSICION FINAL DE RESIDUOS SOLIDOS COMERCIAL','1'], 
          ['DISPOSICION FINAL DE ESCOMBROS DE CONSTRUCCION COMERCIAL','2'], 
          ['DISPOSICION FINAL DE RESTOS DE ANIMALES COMERCIAL','3'], 
          ['DISPOSICION FINAL DE RAMAS Y DESECHOS DE JARDINERIA COMERCIAL','4'],
          ['DISPOSICION FINAL DE LLANTAS DE VEHICULOS AUTOMORES COMERCIAL','5'],
          ['DISPOSICION FINAL DE LODO ESTABILIZADOS DERIVADO DE PLANTAS DE TRATAMIENTO','6']
        ], {:include_blank => true}, {class:'btn btn-default dropdown-toggle services'} %>
      </div>
      <div class='col-xs-3 col-md-2'>
        <br>
        <%= link_to '', insertServices_enteros_path, class:'btn btn-default btn-sm glyphicon glyphicon-plus-sign btnplus', remote:true %>
        <%= link_to '', enteros_path, class:'btn btn-default glyphicon glyphicon-list btn-sm' %>
        <%= link_to '', deleteServices_enteros_path, class:'btn btn-default btn-sm glyphicon glyphicon-trash btnrm', remote:true %>
        <%= link_to '', buildpdf_enteros_path(format:'js'), class:'btn btn-default btn-sm glyphicon glyphicon-print generate', remote:true %>
        
      </div>
    </div>
    <div class="row">
      <div class="col-xs-8 col-md-7">
        <div class="table-responsive mytable">
          <table class="table table-hover table-striped display">
            <thead>
              <tr>
                <td>ID</td>
                <td>TIPO</td>
                <td>COSTO</td>
                <td>ADICIONAL</td>
                <td>TOTAL</td>
              </tr>
            </thead>
            <tbody class="tbone">
              
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class='container tag'>
  <div class='row'>
    <div class='col-xs col-md-12 be-gray pdfcol'>
      <iframe id='myIframe' src=''  style="border: 0"  width="100%" height="600" frameborder="0" scrolling="no"></iframe>
    </div>
  </div>
</div>

app/views/enteros/_services.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs col-md">
      <div class="table-responsive no-margins">
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th>NOMBRE</th>
              <th>SERVICIO</th>
              <th>UNIDAD</th>
              <th>CANTIDAD</th>
              <th>COSTO</th>
              <th>30% ADICIONAL</th>
              <th>TOTAL</th>
            </tr>
          </thead>
          <tbody>
          <% @enteros.each do |entero| %>
            <tr>
              <td><%= entero.taxpayer %></td>
              <td><%= entero.service %></td>
              <td><%= entero.unit %></td>
              <td><%= entero.quantity %></td>
            </tr>
          <% end %>
        </tbody>
        </table>
      </div>
    </div>
  </div>  
</div>

app/views/enteros/buildPdf.js.erb
var $rows = $('.tbone').find('tr');
var enteros = [];

$rows.each(
  function(i,el){
    var $col = $(this).find('td');
    enteros.push($col.eq(0).text());
  });
console.log();
var url = '/enteros/showEntero?totals=' + enteros + '&tocken=' + $('input#token').val() +'&f=' + $('input#f').val();

$('#myIframe').attr("src", url);
$('.tag').show();
$('.pdfcol').show();
//window.location.href=url;

app/views/enteros/deleteServices.js.erb
var id = $('.display').find('tr:last td:first').text();
var serviceID = $('.tbone').find('tr:last td:eq(1)').text();
$.ajax({
    type:'DELETE',
    url:'/enteros/popService',
    dataType:'json',
    data: { id: id }
    ,success: function(data)
    {
        $('.services option[value="'+serviceID+'"]').removeAttr('disabled');
        $('.display tr:last').remove();
        var rowCount = $('.tbone').children('tr').length;
        if (rowCount == 0)
        {
            $('.btnrm').hide();
            $('.generate').hide();
            $('.tag').hide();
            $('#taxpayer').prop('disabled',false);
        }
        
        if( rowCount <= 6 && rowCount >= 1)
        {
            $('.btnplus').show();
            $('.generate').show();
        }
    }
    ,error:function(data)
    { 
        console.log(data); debugger; 
    }
});

app/views/enteros/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs col-md-12">
            <h1>Editar Entero</h1>
        </div>
    </div>
</div>

<%= render 'form' %>

<%= link_to 'Mostrar', @entero, class:'btn btn-default btn-sm' %> |
<%= link_to 'Regresar', enteros_path, class:'btn btn-default btn-sm' %>

app/views/enteros/index.html.erb
<div class="container">
 <!-- <div class="row">
    <div class="col-xs col-md">
      <%#= notice %>
    </div>
  </div> -->
  <div class="row">
    <div class="col-xs col-md">
      <h1>Listado de Enteros</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-xs col-md-10">
      <div class="table-responsive no-margins">
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th>NOMBRE</th>
            <!--  <th>SERVICIO</th>
              <th>UNIDAD</th>
              <th>CANTIDAD</th> -->
              <th>FECHA ULTIMO REGISTRO</th>
              <th>FOLIO ENTERO</th>
            <!--  <th>COSTO</th>
              <th>30% ADICIONAL</th>
              <th>TOTAL</th> -->
              <th colspan="1"></th>
            </tr>
          </thead>
          <tbody>
            <% @enteros.each do |entero| %>
              <%# case entero.service %>
              <%# when '1' %>
              <%# servicio = 'RESIDUOS SOLIDOS COMERCIAL' %>
              <%# when '2' %>
              <%# servicio = 'ESCOMBROS DE CONSTRUCCION COMERCIAL' %>
              <%# when '3' %>
              <%# servicio = 'RESTOS DE ANIMALES COMERCIAL' %>
              <%# when '4' %>
              <%# servicio = 'RAMAS Y DESECHOS DE JARDINERIA COMERCIAL' %>
              <%# when '5' %>
              <%# servicio = 'LLANTAS DE VEHICULOS AUTOMORES COMERCIAL' %>
              <%# when '6' %>
              <%# servicio = 'LODO ESTABILIZADOS DERIVADO DE PLANTAS DE TRATAMIENTO' %>
              <%# end %>
              <tr>
                <td><%= entero.taxpayer %></td>
              <!--  <td><%#= servicio %></td>
                <td><%#= entero.unit %></td>
                <td><%#= entero.quantity %></td> -->
                <td>
                  <%= entero.created_at %>
                  <%#= entero.created_at.strftime("%d/%m/%Y") %>
                  </td>
                  <td><%= entero.folio %></td>
                  <td>
                    <% if entero.folio %>
                      <%= link_to 'Mostrar', entero_path(entero,format:'pdf'), class:'btn btn-default btn-xs' %>
                    <% else %>
                      <%= link_to 'Mostrar', entero, class:'btn btn-default btn-xs' %>
                    <% end %>
                  </td>
               <!-- <td><%#= link_to 'Editar', edit_entero_path(entero), class:'btn btn-default btn-xs' %></td>
                <td><%#= link_to 'Borrar', entero, method: :delete, data: { confirm: 'Esta usted seguro?' }, class:'btn btn-default btn-xs' %></td>
                -->
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 col-md-2">
      <%= link_to 'NUEVO', new_entero_path, class:'btn btn-default btn-lg be-round_soft_gray' %>
    </div>
    <div class='col-xs-8 col-md-8'>
      <%= will_paginate @enteros %>
    </div>
  </div>
</div>

app/views/enteros/insertServices.js.erb
var concessionary = $('#taxpayer').val();
var serviceID = $('.services option:selected').val();
var folio = $('#f').val();
var token = $('#token').val();
//var uma = 75.49;
//var uma = 80.60;
//var uma = 84.49;
var uma = 86.88;
if(serviceID != '')
{
    var units = $('.unit option:selected').text();
    var quantities = $('.cantidad').val();
    //console.log(quantities);
    //console.log(units);
    if($.isNumeric(quantities))
    {
        switch(serviceID)
        {
            case '1':
                //tax = 320.16;
                tax = uma*4;
                break;
            case '2':
                //tax = 400.2;
                tax = uma*5;
                break;
            case '3':
                //tax = 240.12;
                tax = uma*3;
                break;
            default:
                    tax=75.49;
        }
        
        if(units == 'K.G.')
            quantities = quantities * 0.001;

        var payment = Math.round(tax*quantities);
        var percent = Math.round(payment*0.3);
        var total = percent + payment;
        quantities = $('.cantidad').val();
        var rowCount = $('.tbone').children('tr').length;
        
        if( rowCount <= 5)
        {
            $('.unit').val(1);                                         //SELECT TON
            $('.cantidad').val('');
            $('.services').val('');                                    //establish the value
            $('.generate').show();
            $.ajax({
                type:'POST'
                ,url:'/enteros/putService'
                ,dataType:'json'
                ,cache: false
                ,data: { entero: { taxpayer: concessionary, service: serviceID, unit: units, quantity: quantities, token:token, folio:folio } }
                ,success: function(data){
                    $('.display').find('tbody:last').append('<tr><td>'+data.id+'</td><td>'+serviceID+'</td><td>'+payment+'</td><td>'+percent+'</td><td>'+total+'</td></tr>');
                    $('.btnrm').show();
                    //$('#taxpayer').prop('disabled',true);
                    $('.services option[value="'+serviceID+'"]').attr('disabled','disabled');
                }
                ,error:function(data) { console.log(data); }
            });
        }
        else
        {
            alert('no se pueden agregar mas de 6 servicios ultimo servicio eliminado');
            $('.generate').hide();
            $('.btnplus').hide();
        }
    }
    else
    {
        alert('proporcionar solo numeros!');
        $('.cantidad').val('');
    }
}
else
{
    alert('Debe seleccionar un servicio para poder continuar');
}

app/views/enteros/new.html.erb
<div class="container be-round_soft_gray">
    <div class="row">
        <div class="col-xs col-md-12">
            <h1>Generar Entero</h1>
        </div>
    </div>
</div>


<%= render 'form' %>

app/views/enteros/putService.js.erb
//$('.display').find('tr').each(function(){
//    $(this).find('td').eq(0).before('<td>BINGO</td>');
//});
//    $('form#new_entero').submit();
$('.display').find('tbody:last').append('<tr><td>'+payment+'</td><td>'+payment*0.3+'</td><td>'+(payment+payment*0.3)+'</td></tr>');
$('.cantidad').val('');
$('.services').val(1);

app/views/enteros/show.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xs col-md-6">
      <p id="notice"><%= notice %></p>
      <p>
        <strong>NOMBRE:</strong>
        <%= @entero.taxpayer %>
      </p>
      <p>
        <% factor = 75.49 %>
        <% case @entero.service %>
        <% when '1' %>
        <%   servicio = 'RESIDUOS SOLIDOS COMERCIAL' %>
        <%   tax = 4*factor %>
        <% when '2' %>
        <%   servicio = 'ESCOMBROS DE CONSTRUCCION COMERCIAL' %>
        <%   tax = 5*factor %>
        <% when '3' %>
        <%   servicio = 'RESTOS DE ANIMALES COMERCIAL' %>
        <%   tax = 1*factor %>
        <% when '4' %>
        <%   servicio = 'RAMAS Y DESECHOS DE JARDINERIA COMERCIAL' %>
        <%   tax = factor %>
        <% when '5' %>
        <%   servicio = 'LLANTAS DE VEHICULOS AUTOMORES COMERCIAL' %>
        <%   tax = factor %>
        <% when '6' %>
        <%   servicio = 'LODO ESTABILIZADOS DERIVADO DE PLANTAS DE TRATAMIENTO' %>
        <%   tax = factor %>
        <% end %>
        <% @entero.quantity ? cost = @entero.quantity * tax : cost=0 %>
        <% adition = cost * 0.3 %>
        <% tot = cost + adition %>
        <strong>Service:</strong>
        <%= servicio %>
      </p>
      <p>
        <strong>UNIDAD:</strong>
        <%= @entero.unit %>
      </p>
      <p>
        <strong>CANTIDAD:</strong>
        <%= @entero.quantity %>
      </p>
      <p>
        <strong>COSTO:</strong>
        <%= cost %>
      </p>
      <p>
        <strong>ADICIONAL:</strong>
        <%= adition %>
      </p>
      <p>
        <strong>TOTAL:</strong>
        <%= tot %>
      </p>
      <br>
      <%= link_to 'EDITAR', edit_entero_path(@entero), class:'btn btn-default btn-sm' %> |
      <%= link_to 'REGRESAR', enteros_path, class:'btn btn-default btn-sm' %>

    </div>
  </div>
</div>