config/routes.rb
Rails.application.routes.draw do
  get 'debts/new'

  
  root 'enteros#new'
  resources :sessions, only:[:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  
  resources :enteros do
      collection do
        get 'showRecipts', to: 'enteros#showRecipts'
        get 'buildpdf', to:'enteros#buildPdf'
        get 'showEntero', to:'enteros#showEntero'
        get 'insertServices', to:'enteros#insertServices'
        get 'deleteServices', to:'enteros#deleteServices'
        post 'putService', to:'enteros#putService'
        delete 'popService', to:'enteros#popService'
      end
  end
  
  resources :concessionaries do
    collection do
      get 'get_byName', to:'concessionaries#get_byName'
    end
  end
  
  resources :vehicles do
      resources :debts, only: [:create, :destroy]
  end
  

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :concessionary
  has_many :debts
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all.paginate(page: params[:page], per_page:20)
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    #byebug
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehiculo agregado.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehiculo datos actualizado.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehiculo eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:plate, :concessionary_id)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class='container'>
  <div class='row'>
    <div class='col-xs-4 col-md-6'>
      <%= f.label :Concesionario %><br>
      <%= f.collection_select(:concessionary_id, Concessionary.all, :id, :name,
      {:include_blank => true}, {class:'btn btn-default dropdown-toggle'} ) %>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-2 col-md-2'>
      <%= f.label :Placas %><br>
      <%= f.text_field :plate, class:'form-control' %>
    </div>
  </div>
  <div class='row'>
    <div class="col-xs-2 col-md-2">
      <br>
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/vehicles/edit.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs col-md-12 be-soft_gray'>
            <h1>Edicion de Vehiculos</h1>            
        </div>
    </div>
</div>

<%= render 'form' %>
<br>
<div class='container'>
    <div class='row'>
        <div class='col-xs col-md-12 be-soft_gray'>
            <br>
            <%= link_to 'Mostrar', @vehicle, class:'btn btn-default btn-sm' %> |
            <%= link_to 'Regresar', vehicles_path, class:'btn btn-default btn-sm' %>
        </div>
    </div>
</div>

app/views/vehicles/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs col-md-12 be-soft_gray'>
      <h1>Lista de Vehiculos de Concesionarios</h1>      
    </div>
  </div>
  <div class='row'>
    <div class='col-xs col-md-8'>
      <div class="table-responsive no-margins">
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th>Concesionario</th>
              <th>Placa</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <% @vehicles.each do |vehicle| %>
              <tr>
                <td><%= vehicle.concessionary.name %></td>
                <td><%= vehicle.plate %></td>
                <td><%= link_to vehicle do %> <%= octicon 'eye', class:'rigth' %> <% end %></td>
                <td><%= link_to edit_vehicle_path(vehicle) do %> <%= octicon 'pencil', class:'rigth' %> <% end %> </td>
                <td><%= link_to vehicle, method: :delete, data: { confirm: 'Esta usted seguro?' } do %>
                    <%= octicon 'trashcan', class:'rigth' %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs col-md-4'>
      <br>
      <%= link_to 'Nuevo Vehiculo', new_vehicle_path, class:'btn btn-default btn-md' %>
    </div>
    <div class='col-xs col-md-8'>
      <%= will_paginate @vehicles, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div

app/views/vehicles/new.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs col-md-12 be-soft_gray'>
            <h1>Nuevo Vehiculo</h1>
        </div>
    </div>
</div>
<%= render 'form' %>
<br>
<br>
<div class='container'>
    <div class='row'>
        <div class='col-xs col-md-12 be-soft_gray'>
            <%= link_to 'Regresar', vehicles_path, class:'btn btn-default btn-lg' %>            
        </div> 
    </div>
</div>

app/views/vehicles/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs col-md-6'>
      <%= content_tag(:p, content_tag(:strong, "Concesionario: #{@vehicle.concessionary.name}"  )) %>
      <%= content_tag(:p, content_tag(:strong, 'Placa')) %>
      <%= @vehicle.plate %>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs col-md-12'>
      <br>
      <%= render @vehicle.debts  %>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs col-md-12 be-soft_gray'>
      <%= link_to 'Editar', edit_vehicle_path(@vehicle), class:'btn btn-default btn-lg' %> |
      <%= link_to 'Regresar', vehicles_path, class:'btn btn-default btn-lg' %>
    </div>
  </div>
</div>