config/routes.rb
Rails.application.routes.draw do
  get 'debts/new'

  
  root 'enteros#new'
  resources :sessions, only:[:new, :create, :destroy]
  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  
  resources :enteros do
      collection do
        get 'showRecipts', to: 'enteros#showRecipts'
        get 'buildpdf', to:'enteros#buildPdf'
        get 'showEntero', to:'enteros#showEntero'
        get 'insertServices', to:'enteros#insertServices'
        get 'deleteServices', to:'enteros#deleteServices'
        post 'putService', to:'enteros#putService'
        delete 'popService', to:'enteros#popService'
      end
  end
  
  resources :concessionaries do
    collection do
      get 'get_byName', to:'concessionaries#get_byName'
    end
  end
  
  resources :vehicles do
      resources :debts, only: [:create, :destroy]
  end
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Disposicion de Residuos Municipales</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <section id="myheader">
    <div class="container be-gray">
      <div class="row">
        <div class="col-xs col-md-12">
          <% if logged_in? %>
            <span class="pull-left">
              usuario [ <%= current_user.name.upcase %> ]
            </span>
            <span class="pull-right">
              <%= link_to "", root_path, class:'btn btn-default btn-sm glyphicon glyphicon-home be-round_soft_gray' %>
              <%= link_to "CONCESIONARIOS", concessionaries_path, class:'btn btn-sm be-round_soft_gray' %>
              <%= link_to "VEHICULOS", vehicles_path, class:'btn btn-sm be-round_soft_gray' %>
              <%= link_to "ENTEROS", enteros_path, class:'btn btn-sm be-round_soft_gray' %>
             	<%= link_to "Logout", logout_path, method: :delete, class:'btn btn-sm btn-danger' %> 
              <span class="glyphicon glyphicon-log-in"></span>
            </span>
          <% end %>
          <br>
          <% flash.each do |key, value| %>
             <p id='<%= key %>'><%= value %></p>
          <% end %>
          <%#= logged_in? %>
        </div>
      </div>
    </div>
  </section>
<%= yield %>

</body>
</html>